.github/ISSUE_TEMPLATE/feature_request.md
=> issue template 

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REUQEST_TEMPLATE.md
issue template 생성
pull request
feature
bug
=> Issue template

Android/.idea/misc.xml, Android/app/src/main/AndroidManifest.xml, Android/app/src/main/java/com/example/squadmap/ui/bottommenu/BottomNavigation.kt, Android/app/src/main/java/com/example/squadmap/ui/home/HomeScreen.kt, Android/app/src/main/java/com/example/squadmap/ui/navigation/SquadMapNavGraph.kt, Android/app/src/main/java/com/example/squadmap/ui/navigation/SquadMapNavigation.kt, Android/app/src/main/java/com/example/squadmap/ui/search/SearchScreen.kt, Android/app/src/main/java/com/example/squadmap/ui/utils/SquadMapIcons.kt
=> [Android] FEAT: Search 화면 생성과 연결

FE/src/components/common/LoadingSpinner/LoadingSpinner.stories.tsx, FE/src/components/common/LoadingSpinner/LoadingSpinner.style.ts, FE/src/components/common/LoadingSpinner/index.tsx
로딩 컴포넌트를 사용해야하는 홈 페이지로 인하여 브랜치 합치는 과정을 진행
=> [FE] 홈 관련 브랜치 Update 하기 위한 PR

FE/.storybook/preview.js, FE/package.json, FE/src/App.tsx, FE/src/components/GridCards/GridCards.stories.tsx, FE/src/components/GridCards/index.tsx, FE/src/components/common/LoadingSpinner/LoadingSpinner.stories.tsx, FE/src/components/common/LoadingSpinner/LoadingSpinner.style.ts, FE/src/components/common/LoadingSpinner/index.tsx, FE/src/constants/dummyData.js, FE/src/mocks/handlers/index.js, FE/src/pages/Home/Home.stories.tsx, FE/src/pages/Home/index.tsx, FE/src/pages/MyPage/Detail/index.tsx, FE/src/pages/MyPage/index.tsx, FE/yarn.lock
=> [FE] Home 브랜치 FE에 병합

FE/src/components/GridCards/GridCards.stories.tsx, FE/src/components/GridCards/GridCards.style.ts, FE/src/components/GridCards/index.tsx, FE/src/components/common/Card/Card.style.ts, FE/src/components/common/Header/index.tsx, FE/src/components/common/Text/Text.style.ts
기존 Component 수정 ( Card, Header, Text, GridCards Component )
=> [FE] Component 수정

FE/src/components/GridCards/GridCards.stories.tsx, FE/src/components/GridCards/GridCards.style.ts, FE/src/components/GridCards/index.tsx, FE/src/components/common/Card/Card.style.ts, FE/src/components/common/Header/index.tsx, FE/src/components/common/Text/Text.style.ts
refactor: Card, Header, Text, GridCards Component CSS 조정 및 Props 변경
=> [FE] 컴포넌트 수정한것들 FE 브랜치에 병합

FE/src/pages/Home/Home.stories.tsx, FE/src/pages/Home/index.tsx
refactor: Home Page story msw 연동, Card에 링크 해당 맵에 대한 달기
=> [FE] Home Component msw 연동, 링크 컴포넌트 추가 하여 카드 링크 연결

FE/src/components/Input/index.tsx, FE/src/components/common/Header/Navigation/Navigation.style.ts, FE/src/components/common/Icon/Icon.style.ts, FE/src/components/common/Icon/index.tsx, FE/src/mocks/handlers/index.js, FE/src/pages/Home/index.tsx
약간의 스타일링 수정, mock API 추가, 반복문으로 인해 생성된 컴포넌트 key 설정해주기
=> [FE] 기존 컴포넌트 스타일링 수정 작업

FE/.eslintrc.js, FE/src/components/Login/index.tsx, FE/src/components/Manual/Manual.style.ts, FE/src/components/Manual/index.tsx, FE/src/components/ReportError/ReportErrror.style.ts, FE/src/components/ReportError/index.tsx, FE/src/components/common/GlobalModal/GlobalModal.style.ts, FE/src/components/common/GlobalModal/index.tsx, FE/src/components/common/Header/Navigation/Navigation.style.ts, FE/src/components/common/Header/Navigation/index.tsx, FE/src/components/common/Header/index.tsx, FE/src/components/common/Overlay/Overlay.style.ts, FE/src/components/common/Overlay/index.tsx
사용설명서, 오류사항 제보 모달창은 UI틀만 잡아놓고 기획 해야함
=> [FE] 네비게이션 기능 구현 적용

Android/app/build.gradle, Android/app/src/main/AndroidManifest.xml, Android/app/src/main/java/com/example/squadmap/SquadMapApp.kt, Android/app/src/main/java/com/example/squadmap/common/AppSession.kt, Android/app/src/main/java/com/example/squadmap/data/model/JWT.kt, Android/app/src/main/java/com/example/squadmap/ui/MainActivity.kt, Android/app/src/main/java/com/example/squadmap/ui/bottommenu/BottomNavigation.kt, Android/build.gradle
=> [Android] FEAT: 비 로그인 상태로 프로필, 나의 지도 탭으로 이동시 로그인 화면으로 이동

FE/src/apis/mypage.ts, FE/src/hooks/UseLogin.ts, FE/src/pages/MyPage/Form/index.tsx, FE/src/types/mypage.ts, FE/src/utils/cookie.ts
=> 🚧 feat: 지도 생성 시 authority 옵션 추가, cookie 관련 코드 util로 관리

Android/app/build.gradle, Android/app/src/main/AndroidManifest.xml, Android/app/src/main/java/com/example/squadmap/data/model/CategoryInfo.kt, Android/app/src/main/java/com/example/squadmap/data/model/StoreInfo.kt, Android/app/src/main/java/com/example/squadmap/ui/MainActivity.kt, Android/app/src/main/java/com/example/squadmap/ui/bottommenu/BottomNavMenu.kt, Android/app/src/main/java/com/example/squadmap/ui/bottommenu/BottomNavigation.kt, Android/app/src/main/java/com/example/squadmap/ui/home/HomeScreen.kt, Android/app/src/main/java/com/example/squadmap/ui/home/MapTypeChip.kt, Android/app/src/main/java/com/example/squadmap/ui/map/StoreMap.kt, Android/app/src/main/java/com/example/squadmap/ui/navigation/SquadMapNavGraph.kt, Android/app/src/main/java/com/example/squadmap/ui/navigation/SquadMapNavigation.kt, Android/app/src/main/java/com/example/squadmap/ui/store/StoreList.kt, Android/app/src/main/java/com/example/squadmap/ui/theme/Shape.kt, Android/app/src/main/java/com/example/squadmap/ui/utils/Logger.kt, Android/app/src/main/java/com/example/squadmap/ui/web/WebView.kt, Android/build.gradle, Android/gradle.properties, Android/settings.gradle
ui 수정
navigation graph 통합
지도 스크린 구현
#68
=> [Android] feat: 지도 구현 

Android/app/build.gradle, Android/app/src/main/AndroidManifest.xml, Android/app/src/main/java/com/example/squadmap/ui/login/LoginScreen.kt, Android/app/src/main/java/com/example/squadmap/ui/map/StoreMap.kt, Android/app/src/main/java/com/example/squadmap/ui/navigation/SquadMapNavGraph.kt, Android/app/src/main/java/com/example/squadmap/ui/navigation/SquadMapNavigation.kt, Android/app/src/main/java/com/example/squadmap/ui/web/WebView.kt, Android/app/src/main/res/drawable/ic_baseline_arrow_back_ios_24.xml
#73 
배포 후 code 받아오는 작업 마무리하면 구현 완료
=> feat: github login 임시로 구현 아직 코드를 받아오지는 못함

Android/app/src/main/java/com/example/squadmap/common/Logger.kt, Android/app/src/main/java/com/example/squadmap/ui/MainActivity.kt, Android/app/src/main/java/com/example/squadmap/ui/home/HomeScreen.kt, Android/app/src/main/java/com/example/squadmap/ui/map/MapViewModel.kt, Android/app/src/main/java/com/example/squadmap/ui/map/StoreMap.kt, Android/app/src/main/java/com/example/squadmap/ui/map/store/StoreList.kt, Android/app/src/main/java/com/example/squadmap/ui/navigation/SquadMapNavGraph.kt, Android/app/src/main/java/com/example/squadmap/ui/search/SquadMapIcons.kt, Android/app/src/main/java/com/example/squadmap/ui/web/WebView.kt
=> feat: 지도 아래 가게 목록 구현

FE/src/App.tsx, FE/src/components/RecentSearch/RecentSearch.style.ts, FE/src/components/RecentSearch/index.tsx, FE/src/interfaces/ISearchPlace.ts, FE/src/pages/MyMap/Header/Header.style.ts, FE/src/pages/SearchMap/PlaceInfos/Infos.style.ts, FE/src/pages/SearchMap/PlaceInfos/index.tsx, FE/src/pages/SearchMap/SearchMap.style.ts, FE/src/pages/SearchMap/SearchPlace/SearchPlace.style.ts, FE/src/pages/SearchMap/SearchPlace/index.tsx, FE/src/pages/SearchMap/index.tsx, FE/src/recoil/atoms/searchplace.ts
다음 작업 : 더미데이터를 실제 네이버 api 데이터로 수정하는 작업 진행.
=> 🚧 feat: 장소 관련 페이지 검색 UI 완료, 더미데이터 출력

Android/app/src/main/java/com/example/squadmap/data/datasource/StoreSearchDataSource.kt, Android/app/src/main/java/com/example/squadmap/data/datasource/StoreSearchDataSourceImpl.kt, Android/app/src/main/java/com/example/squadmap/data/dto/StoreSearchResultDTO.kt, Android/app/src/main/java/com/example/squadmap/data/model/Coordinate.kt, Android/app/src/main/java/com/example/squadmap/data/model/MapInfo.kt, Android/app/src/main/java/com/example/squadmap/data/model/ResultStore.kt, Android/app/src/main/java/com/example/squadmap/data/repository/StoreSearchRepository.kt, Android/app/src/main/java/com/example/squadmap/data/repository/StoreSearchRepositoryImpl.kt, Android/app/src/main/java/com/example/squadmap/network/StoreSearchApi.kt, Android/app/src/main/java/com/example/squadmap/ui/addstore/AddStoreViewModel.kt, Android/app/src/main/java/com/example/squadmap/ui/addstore/StoreDescriptionScreen.kt, Android/app/src/main/java/com/example/squadmap/ui/addstore/StoreSearchScreen.kt, Android/app/src/main/java/com/example/squadmap/ui/common/navigation/SquadMapNavGraph.kt, Android/app/src/main/java/com/example/squadmap/ui/home/HomeViewModel.kt, Android/app/src/main/java/com/example/squadmap/ui/map/MapViewModel.kt, Android/app/src/main/java/com/example/squadmap/ui/map/StoreMapScreen.kt
=> [Android] feat: 장소 검색 페이징 구현

Android/app/src/main/java/com/example/squadmap/data/model/MapInfo.kt, Android/app/src/main/java/com/example/squadmap/ui/MainActivity.kt, Android/app/src/main/java/com/example/squadmap/ui/addstore/StoreSearchScreen.kt, Android/app/src/main/java/com/example/squadmap/ui/common/navigation/SquadMapNavigation.kt, Android/app/src/main/java/com/example/squadmap/ui/map/MapViewModel.kt, Android/app/src/main/java/com/example/squadmap/ui/map/store/StoreListScreen.kt, Android/app/src/main/java/com/example/squadmap/ui/web/WebView.kt
#103 
문제 수정
URl을 보낼때는 Encode를 해야했다.
=> fix: 웹뷰 종료 버그 수정

FE/src/apis/group.ts, FE/src/constants/key.ts, FE/src/pages/MyPage/Authority/Authority.style.ts, FE/src/pages/MyPage/Authority/GroupInfo/GroupInfo.style.ts, FE/src/pages/MyPage/Authority/GroupInfo/index.tsx, FE/src/pages/MyPage/Authority/index.tsx, FE/src/pages/MyPage/Item/index.tsx
키보드 이벤트 발생시 해당 지도 그룹 멤버들을 가져오는 api가 계속 발생한다. 요부분 수정 필요!
=> 🚧 FE: 그룹 관리 인풋 키보드 이벤트 관련 기능 작업 진행, 해당 지도의 그룹 멤버들 가져와서 뿌려주기

BE/src/main/java/com/squadmap/common/auth/AuthInterceptor.java, BE/src/main/java/com/squadmap/common/config/WebConfig.java, BE/src/main/java/com/squadmap/common/config/httpClientConfig.java, BE/src/main/java/com/squadmap/common/excetpion/ErrorStatusCodeAndMessage.java, BE/src/main/java/com/squadmap/core/category/application/CategoryServiceImpl.java, BE/src/main/java/com/squadmap/core/category/domain/Category.java, BE/src/main/java/com/squadmap/core/category/infrastructure/CategoryRepository.java, BE/src/main/java/com/squadmap/core/group/application/GroupMemberServiceImpl.java, BE/src/main/java/com/squadmap/core/group/domain/GroupMember.java, BE/src/main/java/com/squadmap/core/group/domain/PermissionLevel.java, BE/src/main/java/com/squadmap/core/place/application/PlaceServiceImpl.java, BE/src/main/java/com/squadmap/member/domain/Member.java, BE/src/main/java/com/squadmap/member/ui/dto/NicknameUpdateRequest.java, BE/src/test/java/com/squadmap/category/integration/CategoryServiceTest.java, BE/src/test/java/com/squadmap/comment/integration/CommentServiceTest.java, BE/src/test/java/com/squadmap/group/integretion/GroupServiceTest.java, BE/src/test/java/com/squadmap/map/integration/MapServiceTest.java, BE/src/test/java/com/squadmap/member/integration/MemberServiceTest.java, BE/src/test/java/com/squadmap/place/acceptance/PlaceAcceptanceTest.java, BE/src/test/java/com/squadmap/place/integration/PlaceServiceTest.java, BE/src/test/resources/data-script.sql
- 기존 테스트 격리 및 기능 추가로 인한 예외 테스트를 추가하지 않고 진행하였음
- 테스트 시나리오를 작성해서 예외 상황 및 분기 테스트를 통합테스트로 진행
=> [BE] 미비 TEST 추가 

FE/src/components/Map/Infos/index.tsx
=> FE branch merge to main

FE/jest.config.js, FE/package.json, FE/src/components/Category/CreateCategoryModalInfo.tsx, FE/src/components/KaKaoMap/index.tsx, FE/src/components/NickName/NickName.test.tsx, FE/src/components/NickName/index.tsx, FE/src/components/RecentSearch/RecentSearch.test.tsx, FE/src/components/RecentSearch/index.tsx, FE/src/components/SearchMap/SearchPlace/index.tsx, FE/src/mocks/handlers/category.ts, FE/src/mocks/handlers/mypage.ts, FE/src/mocks/handlers/user.ts, FE/src/pages/SearchMap/SearchMap.test.tsx, FE/src/pages/SearchMap/index.tsx, FE/src/tests/category.test.tsx, FE/src/tests/map.test.tsx, FE/src/tests/testing-libaray-utils.tsx
* 🛠 Jest - 테스트코드 짜기 (지도 생성, 지도 수정, 카테고리 생성 완료.)
* 🛠 카테고리 생성, 닉네임수정, 최근검색어 테스트 코드 작성.
=> FE branch merge main

README.md
=> Revert "🚧 FE - README 상세 요약 정리."
